enum ActionTypeKeys {
  WIRETAP_DYNAMICDATA = 'WIRETAP_DYNAMICDATA',
  WIRETAP_FIREBASES = 'WIRETAP_FIREBASES',
  WIRETAP_NOTIFICATION = 'WIRETAP_NOTIFICATION',
  WIRETAP_NOTIFICATION_COUNT = 'WIRETAP_NOTIFICATION_COUNT',
  WIRETAP_OFFLINE = 'WIRETAP_OFFLINE',
  WIRETAP_MARKERDATA = 'WIRETAP_MARKERDATA',
  WIRETAP_STAGE_EVENT_MESSAGE = 'WIRETAP_STAGE_EVENT_MESSAGE',
  WIRETAP_STAGE_MESSAGE = 'WIRETAP_STAGE_MESSAGE',
  WIRETAP_STATICDATA = 'WIRETAP_STATICDATA',
  WIRETAP_STATUS_INITIALIZED = 'WIRETAP_STATUS_INITIALIZED',
  WIRETAP_STATUS_LOADING = 'WIRETAP_STATUS_LOADING',
  WIRETAP_STATUS_UPDATING = 'WIRETAP_STATUS_UPDATING',
  WIRETAP_UPDATE = 'WIRETAP_UPDATE',

  MAP_ZOOM_UPDATE = 'MAP_ZOOM_UPDATE',

  FILTER_HOTLOAD = 'FILTER_HOTLOAD',
  FILTER_DEATHS_OVERLAY = 'FILTER_DEATHS_OVERLAY',
  FILTER_OWNERSHIP_OVERLAY = 'FILTER_OWNERSHIP_OVERLAY',
}

export default ActionTypeKeys
